In [1]:
import pandas as pd
df_agitation_raw = pd.read_csv('../Dataset/Labels.csv')
df_agitation = df_agitation_raw.query(' type == "Agitation" ').copy()
df_agitation['date'] = pd.to_datetime(df_agitation['date'])
df_agitation['dates'] = df_agitation['date'].dt.date
df_agitation

    patient_id                date       type       dates
2        16f4b 2019-04-11 12:00:22  Agitation  2019-04-11
4        16f4b 2019-04-14 12:00:07  Agitation  2019-04-14
5        16f4b 2019-04-15 18:00:24  Agitation  2019-04-15
6        16f4b 2019-04-16 18:00:38  Agitation  2019-04-16
11       16f4b 2019-04-21 12:00:55  Agitation  2019-04-21
..         ...                 ...        ...         ...
587      0d5ef 2019-06-28 18:02:11  Agitation  2019-06-28
588      d7a46 2019-06-28 18:02:21  Agitation  2019-06-28
598      6b29b 2019-06-29 12:00:27  Agitation  2019-06-29
599      95899 2019-06-29 12:01:20  Agitation  2019-06-29
604      95899 2019-06-29 18:01:14  Agitation  2019-06-29

[135 rows x 4 columns]

In [5]:
# get daily count of agitation episodes
daily_counts = df_agitation.groupby(['patient_id', 'dates']).size().reset_index(name='count')

daily_counts.columns = ['patient_id', 'date', 'agitation_counts']
daily_counts.to_csv('../output/data_cleaned/agitation_daily_counts.csv', index=False)
daily_counts

    patient_id        date  agitation_counts
0        099bc  2019-06-10                 1
1        0cda9  2019-05-28                 1
2        0d5ef  2019-05-23                 1
3        0d5ef  2019-05-24                 1
4        0d5ef  2019-05-25                 2
..         ...         ...               ...
110      ec812  2019-05-06                 1
111      ec812  2019-05-11                 1
112      ec812  2019-06-07                 1
113      ec812  2019-06-10                 1
114      eca1f  2019-05-23                 1

[115 rows x 3 columns]

In [4]:
# Group by patient_id and count unique time when agitation happened
new_df = df_agitation.groupby('patient_id')['date'].nunique().reset_index()
new_df.columns = ['patient_id', 'number_agitation']

new_df.to_csv('../output/data_cleaned/agitation_number.csv', index=False)
new_df

   patient_id  number_agitation
0       099bc                 1
1       0cda9                 1
2       0d5ef                11
3       16f4b                11
4       201d8                 1
5       393cb                 1
6       3fb61                 2
7       46286                 1
8       6b29b                 2
9       73f7c                33
10      7db78                 8
11      8a835                 3
12      8d0d4                 1
13      93c14                12
14      95899                 2
15      96adf                 1
16      a2849                 6
17      b9d58                 4
18      c5031                12
19      d263a                 1
20      d7a46                 2
21      d93d8                 6
22      e4959                 4
23      e87bd                 1
24      e8a78                 3
25      ec812                 4
26      eca1f                 1